### PR TITLE
Make `install` an optional dependency and add 32-bit arm targets

### LINKED ISSUE #1284: Install script does not work on Raspberry Pi Zero
Running the script (the first time) returns the following error:
```sh
pi@raspberrypi:~ $ curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to DEST
install: error: Could not determine target from output of `uname -m`-`uname -s`, please use `--target`: armv6l-Linux
```

Running it again or with sudo won't return anything:
```sh
pi@raspberrypi:~ $ curl --proto '=https' --tlsv1.2 -sS^Chttps://just.systems/install.sh | bash -s -- --to DEST
pi@raspberrypi:~ $ sudo curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to DEST
pi@raspberrypi:~ $ 
```

OS/Arch:
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux
```

### PR DESCRIPTION
**Pull request by CramBL**
Resolves #1284 

Believe it or not, some Linux embedded device will not have `install` installed. This is not uncommon when they have a custom distribution build with Buildroot or Yocto, such devices typically have `cp` and `chmod` though, so when `install` is not available, there's now a fall back to cp and chmod. 

Then I added 32-bit arm targets, that includes old Raspberry Pi models but also various embedded linux devices such as Xilinx Zynq family.

### CODE REVIEW

**Comment by CramBL** [comment]
It is tested on a Zynq-7000 which has this output for `uname -a`:
```
Linux hostname 5.15.19-xilinx-v2022.1 #1 SMP PREEMPT Wed Aug 24 06:33:16 UTC 2022 armv7l GNU/Linux
```
This device does not have `install`.

**Comment by CramBL** [comment]
Now also tested on Raspberry PI 0 which has this `uname -a` output

```shell
Linux hostname 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
```

File: www/install.sh [hunk 1]
```diff
@@ -51,6 +51,19 @@ need() {
   fi
 }
 
+need_one_of() {
```
Comment (casey) [inline www/install.sh]: This can be reverted.

File: www/install.sh [hunk 2]
```diff
@@ -62,6 +75,17 @@ download() {
   fi
 }
 
+install_just() {
```
Comment (casey) [inline www/install.sh]: This can be reverted.

File: www/install.sh [hunk 3]
```diff
@@ -93,14 +117,10 @@ while test $# -gt 0; do
   shift
 done
 
-command -v curl > /dev/null 2>&1 ||
-  command -v wget > /dev/null 2>&1 ||
-  err "need wget or curl (command not found)"
-
-need install
+need_one_of curl wget
```
Comment (casey) [inline www/install.sh]: Doing `need unzip` or `need tar` in the `$target` case statement seems fine to me, instead of adding a `need_one_of` function.

File: www/install.sh [hunk 4]
```diff
@@ -171,7 +193,7 @@ if [ -e "$dest/just" ] && [ "$force" = false ]; then
   err "\`$dest/just\` already exists"
 else
   mkdir -p "$dest"
-  install -m 755 "$td/just" "$dest"
+  install_just "$td/just" "$dest"
```
Comment (casey) [inline www/install.sh]: I don't think there's any particular advantage to using `install` when it's available, so let's just use `cp` and `chmod` directly.

**Review by casey — CHANGES_REQUESTED** [review]
Sounds good to me. I think we should just always use `cp` and `chmod` on unix, since there's no particularly advantage to using `install`. See comments for more details.

**Comment by CramBL** [comment]
Requested changes implemented

**Review by casey — APPROVED** [review]
Nice, LGTM!
