### PR TITLE
Fix powershell shebang, closes #825

### LINKED ISSUE #825: #!powershell.exe does not works
```
set shell := ["powershell.exe", "-c"]

default:
    #!powershell.exe
    Write-Host Hello-World
```
We cannot create powershell shebang because "just" will create tmp script file without any ext

Powershell cannot run script without `.ps1` extension.

Maybe we should support custom extension to created script file.

### PR DESCRIPTION
**Pull request by sigoden**

### CODE REVIEW

**Comment by casey** [comment]
Thanks for the PR!

Can you add a test that this works on windows? Check out the `tests` directory. You can put it in a new module, maybe `tests/shebang.rs`.

Also, what if the users writes:

```
foo:
  #!powershell
```

…without `.exe`. If that works, we should check for that too. Also, do we need to add a suffix for `pwsh.exe`?

Even though this is windows specific, let's do it on every platform. The less platform-specific code there is the better, and it won't hurt to add a `.ps1` suffix on macOS and Linux.

**Comment by sigoden** [comment]
`.exe` extensions is required on windows. So we woudl better use platform-specific code

File: src/platform_interface.rs [hunk 1]
```diff
@@ -11,7 +11,13 @@ pub(crate) trait PlatformInterface {
   ) -> Result<Command, OutputError>;
   
   /// Get generate file ext
-  fn get_recipe_file_ext(command: &str) -> String;
+  fn get_script_file_ext(command: &str) -> &str {
+      if command.ends_with("powershell") {
```
Comment (casey) [inline src/platform_interface.rs]: Should this also check for `powershell.exe`?

```suggestion
      if command.ends_with("powershell") || command.ends_with("powershell.exe") {
```

File: src/platform_interface.rs [hunk 2]
```diff
@@ -11,7 +11,13 @@ pub(crate) trait PlatformInterface {
   ) -> Result<Command, OutputError>;
   
   /// Get generate file ext
-  fn get_recipe_file_ext(command: &str) -> String;
+  fn get_script_file_ext(command: &str) -> &str {
```
Comment (casey) [inline src/platform_interface.rs]: Let's call this `get_script_file_suffix`, to match `std::env::consts::EXE_SUFFIX`.
```suggestion
  fn get_script_file_suffix(command: &str) -> &str {
```

File: src/recipe.rs [hunk 3]
```diff
@@ -129,8 +129,8 @@ impl<'src, D> Recipe<'src, D> {
           io_error: error,
         })?;
       let mut path = tmp.path().to_path_buf();
-      let ext = Platform::get_recipe_file_ext(interpreter);
-      path.push(format!("{}{}", self.name(), ext));
+      let ext_name = Platform::get_script_file_ext(interpreter);
```
Comment (casey) [inline src/recipe.rs]:
```suggestion
      let ext_name = Platform::get_script_file_suffix(interpreter);
```

Comment (casey) [reply src/recipe.rs]:
```suggestion
      let suffix = Platform::get_script_file_suffix(interpreter);
```

File: tests/shebang.rs [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+
+  let output = Command::new(executable_path("just"))
+    .current_dir(tmp.path())
+    .output()
+    .unwrap();
+
+  let stdout = "Hello-World\n";
+
+  assert_stdout(&output, stdout);
+}
```
Comment (casey) [inline tests/shebang.rs]: You can use the `test!` macro. I haven't tested it, but it should be something like this:

```suggestion
#![cfg(windows)]
test! {
  justfile: r#"
  default:
    #!powershell
     Write-Host Hello-World
"#,
  stdout: "Hello-World\n",
}

#![cfg(windows)]
test! {
  justfile: r#"
  default:
    #!powershell.exe
     Write-Host Hello-World
"#,
  stdout: "Hello-World\n",
}
```

File: src/recipe.rs [hunk 5]
```diff
@@ -107,6 +107,20 @@ impl<'src, D> Recipe<'src, D> {
...
+        })?;
+
+      let Shebang {
+        interpreter,
+        argument,
+      } = Shebang::new(shebang_line).ok_or_else(|| RuntimeError::Internal {
+        message: format!("bad shebang line: {}", shebang_line),
+      })?;
+
+
```
Comment (casey) [inline src/recipe.rs]:
```suggestion

```

File: tests/shebang.rs [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+test! {
+  name:     powershell,
+  justfile: r#"
+default:
+  #!powershell
+  Write-Host Hello-World
+"#,
+  stdout: "Hello-World\n",
+}
+
```
Comment (casey) [inline tests/shebang.rs]:
```suggestion

```
